### PR TITLE
Greek language

### PR DESCRIPTION
**Pull request by ConfusedArt**

### CODE REVIEW

**Comment by LightningMods** [comment]
before I merge this see the new string I added just now
https://github.com/LightningMods/Itemzflow-Languages/commit/165b8f71e181fc9f5047d5f858fcaa4ed8b5121f

**Comment by ConfusedArt** [comment]
Will do!

**Comment by ConfusedArt** [comment]
My mistake, I only fixed the typo, will do the strings now

**Comment by ConfusedArt** [comment]
idk how to reopen the request, or if it will reopen by commenting. I replaced a word for a more appropriate one. https://github.com/ConfusedDiscord/Itemzflow-Languages/commit/0b96ad9dbab5f07feab60f9808528dcab8f3f992

**Comment by LightningMods** [comment]
@ConfusedDiscord just make a new pr quickly

**Pull request merged**
